version: "3"
services:
  spark-master:
    build: .
    image: docker-spark:master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark
    command: master

  spark-slave:
    build: .
    image: docker-spark:slave
    ports:
      - "8081:8081"
    networks:
      - spark
    command: slave

networks:
  spark:
